################
POST http://localhost:5000/users/login
Content-Type: application/json

{
  "email": "dharun@gmail.com",
  "password": "123456"
}

############################
# Add New User
POST http://localhost:5000/users/addUser
Content-Type: application/json

{
  "name": "Dharun",
  "username": "dharun123",
  "email": "dharun@gmail.com",
  "password": "123456",
  "contact": 9876543210,
  "admin": false
}


### Example of a protected route using the token
GET http://localhost:5000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQwMTllNzBkNTMzOTM1MjcwYTIyODQiLCJ1c2VybmFtZSI6ImRoYXJ1biIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MTAxMzYwMiwiZXhwIjoxNzQxMDQ5NjAyfQ.dfoIZcn2DT9XgTvDeodPPtNzhWcp-dw9EOBsJ4ni5vU


### Get all users (requires JWT)
GET http://localhost:5000/users/getAllUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQwMTllNzBkNTMzOTM1MjcwYTIyODQiLCJ1c2VybmFtZSI6ImRoYXJ1biIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MTAxMzYwMiwiZXhwIjoxNzQxMDQ5NjAyfQ.dfoIZcn2DT9XgTvDeodPPtNzhWcp-dw9EOBsJ4ni5vU



### Add a new user
POST http://localhost:5000/users/addUser
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@example.com",
  "password": "user1@123",
  "contact":1234567890
}

### Add Details
POST http://localhost:5000/details/postdetails
Content-Type: application/json

{
  "Name": "Dharun",
  "College": "MUthayamal University",
  "Department": "Computer Science",
  "UniqueId":"6bafb93c-544f-4f24-b5e5-3a215c18c482"
  
}



### Get All Details
GET http://localhost:5000/details/getdetails
Content-Type: application/json